// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using toteAPI.Data;

namespace toteAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("toteAPI.Data.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("int");

                    b.Property<string>("Escolaridade")
                        .HasColumnType("longtext");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Escolaridade = "2° Ano",
                            Idade = 17,
                            Nome = "Felipe Ferreira"
                        },
                        new
                        {
                            Id = 2,
                            Escolaridade = "1° Ano",
                            Idade = 15,
                            Nome = "Italo Covas"
                        },
                        new
                        {
                            Id = 3,
                            Escolaridade = "3° Ano",
                            Idade = 18,
                            Nome = "Patrick"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
